### ISSUE TITLE
Mobile (iOS): Allow PodFetch to Run/Play in Background

### ISSUE THREAD

**Issue by saddle-gaudier-06** [SamTV12345/PodFetch#74]
### Clear and concise description of the problem

PodFetch plays well when I have Safari open, but when I leave Safari and go to the home screen or if the screen locks, PodFetch stops playing audio. Then when I switch back to the Safari browser, the podcasts turn back on. It's frustrating because the podcast stops if I start playing a podcast and put my phone in my pocket to walk somewhere. I must always keep the screen on and the Safari window open to listen to podcasts with PodFetch.

### Suggested solution

First, I think this is an awesome project and appreciate all the work that is being put into it. Unfortunately, I don't know the solution to this issue. Though, I hope some of the experts on this project will know a solution. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Thanks for the feedback. I also have this problem on iOS. Because every browser in iOS is built on Webkit it doesn't make a difference which browser you use. On my Android test device I could continue listening with Firefox. They seem to allow continous playback in the background. With iOS I get even errors. When I go to the lock screen, go back to the browser and continue playing and then stop it, it bugs on the playback and doesn't continue properly. I also tested it via SSL and get the same error. 
Curiously YouTube and W3Schools works fine.

**Comment by SamTV12345** [comment]
Should be fixed now. I found the solution and disabled the WebAudio API.

**Comment by SamTV12345** [comment]
Latest tag is available on dockerhub. Just pull the image. It could be that the iPhone caches the webassets. If so you need to reload a couple of times.
